### PR TITLE
205 bug user isnt admin of their personal org

### LINKED ISSUE #205: BUG: User isn't Admin of their personal Org
## Recreation 
- login with your user account
- make sure you are switched to your personal org
- click on Admin > Space Admin
- Screens to add/edit spaces doesn't show.

### PR DESCRIPTION
**Pull request by osala-eng**
## Description

Allow org admin to edit spaces within the org

Fixes #205 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor and code improvement (non-breaking change which improves code quality and/or performance)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation
- [ ] Tests
- [ ] Other chores such as maintenance

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration by modifying the list below.

- [ ] Test A
- [ ] Test B
- [ ] Test C

**Test Configuration**:

Please describe the test setup. List them below as bullet points.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] The commit message follows the convention of this project

### CODE REVIEW

**Comment by janaka** [comment]
Can you elaborate on your solution. Why separate admin page for user vs super admin?

**Comment by osala-eng** [comment]
> Can you elaborate on your solution. Why separate admin page for user vs super admin?

I've removed the empty tabs `Admin Orgs`, `Admin Users` and `Admin User Groups` from being displayed for non super admin users and allowed create/edit in the `Admin Spaces` page
This allows them to create/edit spaces within their `org` but prevents them from creating new orgs or new users

**Comment by janaka** [comment]
Can you drop some screenshots.

Is it still true that a super admin needs to be a member of an org + be assigned admin role? Super admin shouldn't have global adding to everything org scoped. Super admin is only for things that are globally scoped.

**Comment by osala-eng** [comment]
### Screenshots

`Admin Section` for non super admin users

image

`Admin Section` for super admin users

image

**Comment by janaka** [comment]
Ok I see. So I think Admin Users is org scoped?

Also settings has system and org scoped settings. 

So I don't think we can simply separate by tab as it is.

**Review by janaka — APPROVED** [review]
settings is already handled but user admin isn't. Let that in another PR.

**Pull request merged**
